name: qmt_manager
description: Quinmat Manager Project for internal usage (stuff only)
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.8+11


environment:
  sdk: '>=2.19.3 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  utils_component:
    git:
      url: https://github.com/lordyhas/utils_component

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  intl: ^0.18.0
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  equatable: ^2.0.5
  latlong2: ^0.8.1
  font_awesome_flutter: any
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2

  permission_handler: ^10.2.0
  photo_view: ^0.14.0

  #firebase_storage: ^11.0.2
  cloud_firestore: ^4.3.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.3
  #firebase_ui_auth: ^1.1.6
  #flutter_facebook_auth: ^3.3.0+2

  #flutter_facebook_auth: ^5.0.6
  google_sign_in: ^6.1.0

  pedantic: ^1.11.0
  #formz: ^0.6.0
  formz: ^0.4.1
  #google_fonts: ^3.0.1
  google_fonts: ^5.0.0
  meta: ^1.7.0

  badges: ^3.1.1
  url_launcher: ^6.1.6

  image_cropper: ^5.0.0
  image_picker: ^0.8.9
  #image_cropper: ^5.0.0
  local_auth: ^2.1.6
  path_provider: ^2.0.15
  share_plus: ^7.0.2

  package_info_plus: ^4.0.2
  device_info_plus: ^9.0.2
  file_picker: ^5.3.2

  url_strategy: ^0.2.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7

  #flutter_chat_ui: ^1.4.4
  #flutter_chat_ui: ^1.6.8
  flutter_local_notifications: ^13.0.0
  #flutter_app_badger: ^1.5.0

  flutter_markdown: ^0.6.1
  dotted_border: any
  achievement_view: ^1.0.0
  pull_to_refresh: ^2.0.0

  fancy_bottom_navigation_2: ^0.3.5
  #go_router: ^6.0.0
  go_router: ^8.0.5

  http: ^1.0.0

  connectivity_plus: ^4.0.1

  fluent_ui: ^4.6.2
  logger: ^1.4.0
  flutter_easyloading: ^3.0.5



dev_dependencies:
  build_runner: ^2.1.11
  hive_generator: ^2.0.0
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/img/vector_mg1.jpg
    - assets/local/
    - assets/vector/
    - assets/avatar/
    - assets/qp/
    - assets/icon_app.png
    - assets/icon_app_red.png



  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-Regular.ttf
        - asset: fonts/Nunito/Nunito-Italic.ttf
          style: italic
        - asset: fonts/Nunito/Nunito-Bold.ttf
          weight: 700
    - family: Outfit
      fonts:
        - asset: fonts/Outfit/Outfit-Regular.ttf
        - asset: fonts/Outfit/Outfit-Bold.ttf
          weight: 700
    - family: Kalam
      fonts:
        - asset: fonts/Kalam/Kalam-Regular.ttf

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
