List<Map<String,String>> doctorData = [
  {
    "TITLE": "Monsieur",
    "FIRST_NAME": "Michel ",
    "NAME": "E. HINGASE",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Centre Hospitalier Monkole",
    "LOCATION": "Kinshasa",
    "SPECIALITY": "Directeur des Services G\ufffdn\ufffdraux",
    "MOB_NUMBER1": "854682120",
    "MOB_NUMBER2": "",
    "EMAIL1": "mike.hingase@gmail.com ",
    "EMAIL2": "michel.hingase@monkole.cd",
    "Doctor": ""
  },
  {
    "TITLE": "Monsieur",
    "FIRST_NAME": "Jean-Paul",
    "NAME": "ONGALA ",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Centre Hospitalier Monkole",
    "LOCATION": "Kinshasa",
    "SPECIALITY": "Achats et Logistique",
    "MOB_NUMBER1": "890003036",
    "MOB_NUMBER2": "814019368",
    "EMAIL1": "jp.ongala@monkole.cd",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Monsieur",
    "FIRST_NAME": "Henri Espoir",
    "NAME": "Mayembe ",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Centre Hospitalier Monkole",
    "LOCATION": "Kinshasa",
    "SPECIALITY": "Technicien",
    "MOB_NUMBER1": "852296736",
    "MOB_NUMBER2": "812652408",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Madame",
    "FIRST_NAME": "Patricia",
    "NAME": "Malila ",
    "LAST_NAME": "",
    "SEXE": "F",
    "HOSPITAL": "Centre Medical Diamant",
    "LOCATION": "Kinshasa",
    "SPECIALITY": "Directrice des soins infirmiers ",
    "MOB_NUMBER1": "907777780",
    "MOB_NUMBER2": "",
    "EMAIL1": "malila@cmd.cd ",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Monsieur",
    "FIRST_NAME": "Benjamin",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Centre Medical Diamant",
    "LOCATION": "Kinshasa",
    "SPECIALITY": "Technicien",
    "MOB_NUMBER1": "844136664",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Monsieur",
    "FIRST_NAME": "",
    "NAME": "Rahim",
    "LAST_NAME": "Tajdin",
    "SEXE": "M",
    "HOSPITAL": "Centre Medical Diamant",
    "LOCATION": "Kinshasa",
    "SPECIALITY": "Directeur g\ufffdn\ufffdral ",
    "MOB_NUMBER1": "823369351",
    "MOB_NUMBER2": "",
    "EMAIL1": "rahim@cmd.cd",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "",
    "NAME": "Vikas",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Centre Medical Diamant",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "GM",
    "MOB_NUMBER1": "23059219857",
    "MOB_NUMBER2": "",
    "EMAIL1": "vgoya@cmd.cd",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Monsieur",
    "FIRST_NAME": "",
    "NAME": "Sutharson",
    "LAST_NAME": "Thangaman",
    "SEXE": "M",
    "HOSPITAL": "Centre Medical Diamant",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Technicien",
    "MOB_NUMBER1": "919600818694",
    "MOB_NUMBER2": "",
    "EMAIL1": "sthangamani@cmd.cd",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Cedric ",
    "NAME": "Sangwa ",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Clinique Med Parck",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Orthopedique",
    "MOB_NUMBER1": "850766060",
    "MOB_NUMBER2": "",
    "EMAIL1": "cedrickmilindiscott@gmail.com",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Monsieur",
    "FIRST_NAME": "Refren",
    "NAME": "Piana",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Clinique Med Parck",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Lab Biologists ",
    "MOB_NUMBER1": "997269151",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Monsieur",
    "FIRST_NAME": "Patrick",
    "NAME": "WILLIAM",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "CMC",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "CEO",
    "MOB_NUMBER1": "840057288",
    "MOB_NUMBER2": "",
    "EMAIL1": "pwilliam.cmc@forrestgroup.com",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "",
    "NAME": "Arther",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "CMC",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Gyn\ufffdcologue",
    "MOB_NUMBER1": "992385446",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "",
    "NAME": "Cham",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "CMC",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Gyn\ufffdcologue",
    "MOB_NUMBER1": "997040868",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Monsieur",
    "FIRST_NAME": "Jean Claud",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "CMC",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Radiologue",
    "MOB_NUMBER1": "997164698",
    "MOB_NUMBER2": "895533038",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Monsieur",
    "FIRST_NAME": "Daniel",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "CMC",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Technicien",
    "MOB_NUMBER1": "997742862",
    "MOB_NUMBER2": "977515547",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Micheal",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "CMC",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Orthopedique",
    "MOB_NUMBER1": "816352908",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Andre",
    "NAME": "Milangu",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "CMC",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Orthopedique",
    "MOB_NUMBER1": "997112948",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Patrick",
    "NAME": "Muyumba",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "CMC",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Orthopedique",
    "MOB_NUMBER1": "818877709",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Madame",
    "FIRST_NAME": "Carine",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "F",
    "HOSPITAL": "CMC",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Lab Biologists ",
    "MOB_NUMBER1": "841890541",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "",
    "NAME": "Kabeya ",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "CMC ",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "P\ufffddiatrique",
    "MOB_NUMBER1": "814090009",
    "MOB_NUMBER2": "970309999",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Rodolphe",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "CMK-CPU",
    "LOCATION": "Kinshasa",
    "SPECIALITY": "Secr\ufffdtaire de Direction/CMK",
    "MOB_NUMBER1": "898950301",
    "MOB_NUMBER2": "",
    "EMAIL1": "rodolphe.ahmed@cmk-cd.org",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Madame",
    "FIRST_NAME": "Nardin",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "F",
    "HOSPITAL": "Coptik Mission DRC",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Admin",
    "MOB_NUMBER1": "906900793",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "",
    "NAME": "Kerilos",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Coptik Mission DRC",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Anesth\ufffdsiste",
    "MOB_NUMBER1": "906900789",
    "MOB_NUMBER2": "",
    "EMAIL1": "info.drc@coptichospitals.org",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Samuel",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Coptik Mission DRC",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Lab Biologists ",
    "MOB_NUMBER1": "906900753",
    "MOB_NUMBER2": "",
    "EMAIL1": "info.drc@coptichospitals.org",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "",
    "NAME": "Shenouda",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Coptik Mission DRC",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "MD",
    "MOB_NUMBER1": "906900757",
    "MOB_NUMBER2": "",
    "EMAIL1": "info.drc@coptichospitals.org",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "",
    "NAME": "Tshisuz",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Don Bosco Afia",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Anesth\ufffdsiste",
    "MOB_NUMBER1": "813231840",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Reverende",
    "FIRST_NAME": " Soeur Mathilde",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "F",
    "HOSPITAL": "Don Bosco Afia",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "MD",
    "MOB_NUMBER1": "991572483",
    "MOB_NUMBER2": "",
    "EMAIL1": "polyafiadbdirection@gmail.com",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Athos",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Don Bosco Afia",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Orthopedique",
    "MOB_NUMBER1": "842671910",
    "MOB_NUMBER2": "",
    "EMAIL1": "athoslbg3@gmail.com",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Monsieur",
    "FIRST_NAME": "Regis",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Don Bosco Afia",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Radiologue",
    "MOB_NUMBER1": "820380017",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Martin ",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Don Bosco Afia",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Lab Biologists ",
    "MOB_NUMBER1": "816056934",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Monsieur",
    "FIRST_NAME": "Tresor",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Fondation Vie et Sante",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Radiologue",
    "MOB_NUMBER1": "990982584",
    "MOB_NUMBER2": "",
    "EMAIL1": "tlumbu@gmail.com",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Madame",
    "FIRST_NAME": "Delgado",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "F",
    "HOSPITAL": "Fondation Vie et Sante",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "MD",
    "MOB_NUMBER1": "846880318",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Monsieur",
    "FIRST_NAME": "Piro",
    "NAME": "Bukonda",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "GCM",
    "LOCATION": "Likasi",
    "SPECIALITY": "Lab Geologists",
    "MOB_NUMBER1": "815485660",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Monsieur",
    "FIRST_NAME": "",
    "NAME": "Amit",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "HJ Hospitals",
    "LOCATION": "",
    "SPECIALITY": "CEO",
    "MOB_NUMBER1": "",
    "MOB_NUMBER2": "",
    "EMAIL1": "ceo@hjhospitals.org",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Freddy",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "SNCC",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Orthopedique",
    "MOB_NUMBER1": "971030615",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Madame",
    "FIRST_NAME": "Mami",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "F",
    "HOSPITAL": "SNCC",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "",
    "MOB_NUMBER1": "",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Monsieur",
    "FIRST_NAME": "Clement",
    "NAME": "Mbuyu ",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "TFM",
    "LOCATION": "Fungurume",
    "SPECIALITY": "Pharmacien",
    "MOB_NUMBER1": "",
    "MOB_NUMBER2": "",
    "EMAIL1": "cmbuyu@tfm.cmoc.com",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Madame",
    "FIRST_NAME": "",
    "NAME": "Akine Mushind",
    "LAST_NAME": "",
    "SEXE": "F",
    "HOSPITAL": "TFM CLINIC",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Lab Biologists ",
    "MOB_NUMBER1": "851482986",
    "MOB_NUMBER2": "997012578",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Monsieur",
    "FIRST_NAME": "Franck",
    "NAME": "Ilunga",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "WATU WETU",
    "LOCATION": "Kolwezi",
    "SPECIALITY": "",
    "MOB_NUMBER1": "",
    "MOB_NUMBER2": "",
    "EMAIL1": "filunga@wwetu.com",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Madame",
    "FIRST_NAME": "Antoinette",
    "NAME": " ",
    "LAST_NAME": "",
    "SEXE": "F",
    "HOSPITAL": "WHO",
    "LOCATION": "",
    "SPECIALITY": "OMS",
    "MOB_NUMBER1": "810704081",
    "MOB_NUMBER2": "",
    "EMAIL1": "mwendakanyia@who.int",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Professor",
    "FIRST_NAME": "",
    "NAME": "Assumani N.simbo",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Clinique University De Lubumbashi",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Directeur Medicine",
    "MOB_NUMBER1": "997026915",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "",
    "NAME": "Kabeya ",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Mwengezi Hosp",
    "LOCATION": "Kolwezi",
    "SPECIALITY": "",
    "MOB_NUMBER1": "",
    "MOB_NUMBER2": "",
    "EMAIL1": "kabeyakabey@gmail.com",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Gires",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Grand Labo",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Lab Biologists ",
    "MOB_NUMBER1": "991664355",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Alain",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Mwengezi Hospital",
    "LOCATION": "Kolwezi",
    "SPECIALITY": "Medecin Directeur",
    "MOB_NUMBER1": "997022096",
    "MOB_NUMBER2": "",
    "EMAIL1": "kabeyakabey@gmail.com",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Billy",
    "NAME": "Mukonk",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Mwengezi Hospital",
    "LOCATION": "Kolwezi",
    "SPECIALITY": "Surgery",
    "MOB_NUMBER1": "995562253",
    "MOB_NUMBER2": "",
    "EMAIL1": "billymukonk1@gmail.com",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Serge",
    "NAME": "Mwamba",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Mwengezi Hospital",
    "LOCATION": "Kolwezi",
    "SPECIALITY": "",
    "MOB_NUMBER1": "",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Eddy ",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Mwengezi Hospital",
    "LOCATION": "Kolwezi",
    "SPECIALITY": "Labo",
    "MOB_NUMBER1": "977277008",
    "MOB_NUMBER2": "",
    "EMAIL1": "betsheb@gmail.com",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Micheal",
    "NAME": "Kawela",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Mwengezi Hospital",
    "LOCATION": "Kolwezi",
    "SPECIALITY": "Surgery",
    "MOB_NUMBER1": "995894092",
    "MOB_NUMBER2": "",
    "EMAIL1": "kawelmichel@hotmail.com",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Bernard",
    "NAME": "Somona",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "CMOK Hospital",
    "LOCATION": "Kolwezi",
    "SPECIALITY": "Manager General",
    "MOB_NUMBER1": "999505333",
    "MOB_NUMBER2": "",
    "EMAIL1": "bernardtshokomo@yahoo.com",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Alain",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Hospital Methodise ",
    "LOCATION": "Kolwezi",
    "SPECIALITY": "Medecin Directeur",
    "MOB_NUMBER1": "",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Dominique",
    "NAME": "Sangwa",
    "LAST_NAME": "Procopios",
    "SEXE": "M",
    "HOSPITAL": "Hospital Orthodoxe",
    "LOCATION": "Kolwezi",
    "SPECIALITY": "Medecin Directeur",
    "MOB_NUMBER1": "995708040",
    "MOB_NUMBER2": "815054895",
    "EMAIL1": "domisangwa@yahoo.fr",
    "EMAIL2": "domiprokopios@gmail.com",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Eric",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Gecamine Hospital",
    "LOCATION": "Kolwezi",
    "SPECIALITY": "",
    "MOB_NUMBER1": "",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Alain",
    "NAME": "Kabwita",
    "LAST_NAME": "Yav",
    "SEXE": "M",
    "HOSPITAL": "Hospital Methodise ",
    "LOCATION": "Kolwezi",
    "SPECIALITY": "Medecin Directeur",
    "MOB_NUMBER1": "992407179",
    "MOB_NUMBER2": "",
    "EMAIL1": "kabwitaalain@gmail.com",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "",
    "FIRST_NAME": "",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "",
    "HOSPITAL": "",
    "LOCATION": "Kolwezi",
    "SPECIALITY": "",
    "MOB_NUMBER1": "813696957",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Patrick",
    "NAME": "Kas",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Kamoa",
    "LOCATION": "Kolwezi",
    "SPECIALITY": "",
    "MOB_NUMBER1": "818304293",
    "MOB_NUMBER2": "",
    "EMAIL1": "patrickkas@kamoacopper.com",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Monsieur",
    "FIRST_NAME": "Benjamin",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Don Bosco Afia",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "",
    "MOB_NUMBER1": "853446822",
    "MOB_NUMBER2": "997113138",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Christian",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Don Bosco Afia",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "",
    "MOB_NUMBER1": "895419204",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "Docteur",
    "FIRST_NAME": "Martin ",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Don Bosco Afia",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Lab Biologists ",
    "MOB_NUMBER1": "816056934",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": "Yes"
  },
  {
    "TITLE": "",
    "FIRST_NAME": "",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "",
    "HOSPITAL": "Don Bosco Afia",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "Regis Scanner",
    "MOB_NUMBER1": "820380017",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": ""
  },
  {
    "TITLE": "Monsieur",
    "FIRST_NAME": "Ronald ",
    "NAME": "",
    "LAST_NAME": "",
    "SEXE": "M",
    "HOSPITAL": "Don Bosco Afia",
    "LOCATION": "Lubumbashi",
    "SPECIALITY": "",
    "MOB_NUMBER1": "812576045",
    "MOB_NUMBER2": "",
    "EMAIL1": "",
    "EMAIL2": "",
    "Doctor": ""
  }
];


/*
final List<Dessert> _xdesserts = <Dessert>[
    Dessert('Frozen yogurt', 159, 6.0, 24, 4.0, 87, 14, 1),
    Dessert('Ice cream sandwich', 237, 9.0, 37, 4.3, 129, 8, 1),
    Dessert('Eclair', 262, 16.0, 24, 6.0, 337, 6, 7),
    Dessert('Cupcake', 305, 3.7, 67, 4.3, 413, 3, 8),
    Dessert('Gingerbread', 356, 15.0, 49, 3.9, 327, 7, 16),
    Dessert('Jelly bean', 375, 0.0, 94, 0.0, 50, 0, 0),
    Dessert('Lollipop', 392, 0.2, 98, 0.0, 38, 0, 2),
    Dessert('Honeycomb', 408, 3.2, 87, 6.5, 562, 0, 45),
    Dessert('Donut', 452, 25.0, 51, 4.9, 326, 2, 22),
    Dessert('KitKat', 518, 26.0, 65, 7.0, 54, 12, 6),
    Dessert('Frozen yogurt with sugar', 168, 6.0, 26, 4.0, 87, 14, 1),
    Dessert('Ice cream sandwich with sugar', 246, 9.0, 39, 4.3, 129, 8, 1),
    Dessert('Eclair with sugar', 271, 14.0, 26, 6.0, 337, 6, 7),
    Dessert('Cupcake with sugar', 314, 3.7, 69, 4.3, 413, 3, 8),
    Dessert('Gingerbread with sugar', 345, 13.0, 51, 3.9, 327, 7, 16),
    Dessert('Jelly bean with sugar', 364, 0.0, 96, 0.0, 50, 0, 0),
    Dessert('Lollipop with sugar', 401, 0.2, 100, 0.0, 38, 0, 2),
    Dessert('Honeycomb with sugar', 417, 3.2, 89, 6.5, 562, 0, 45),
    Dessert('Donut with sugar', 461, 25.0, 53, 4.9, 326, 2, 22),
    Dessert('KitKat with sugar', 527, 26.0, 67, 7.0, 54, 12, 6),
    Dessert('Frozen yogurt with honey', 223, 6.0, 36, 4.0, 87, 14, 1),
    Dessert('Ice cream sandwich with honey', 301, 9.0, 49, 4.3, 129, 8, 1),
    Dessert('Eclair with honey', 326, 12.0, 36, 6.0, 337, 6, 7),
    Dessert('Cupcake with honey', 369, 3.7, 79, 4.3, 413, 3, 8),
    Dessert('Gingerbread with honey', 420, 11.0, 61, 3.9, 327, 7, 16),
    Dessert('Jelly bean with honey', 439, 0.0, 106, 0.0, 50, 0, 0),
    Dessert('Lollipop with honey', 456, 0.2, 110, 0.0, 38, 0, 2),
    Dessert('Honeycomb with honey', 472, 3.2, 99, 6.5, 562, 0, 45),
    Dessert('Donut with honey', 516, 25.0, 63, 4.9, 326, 2, 22),
    Dessert('KitKat with honey', 582, 26.0, 77, 7.0, 54, 12, 6),
    Dessert('Frozen yogurt with milk', 262, 8.4, 36, 12.0, 194, 44, 1),
    Dessert('Ice cream sandwich with milk', 339, 11.4, 49, 12.3, 236, 38, 1),
    Dessert('Eclair with milk', 365, 18.4, 36, 14.0, 444, 36, 7),
    Dessert('Cupcake with milk', 408, 6.1, 79, 12.3, 520, 33, 8),
    Dessert('Gingerbread with milk', 459, 18.4, 61, 11.9, 434, 37, 16),
    Dessert('Jelly bean with milk', 478, 2.4, 106, 8.0, 157, 30, 0),
    Dessert('Lollipop with milk', 495, 2.6, 110, 8.0, 145, 30, 2),
    Dessert('Honeycomb with milk', 511, 5.6, 99, 14.5, 669, 30, 45),
    Dessert('Donut with milk', 555, 27.4, 63, 12.9, 433, 32, 22),
    Dessert('KitKat with milk', 621, 28.4, 77, 15.0, 161, 42, 6),
    Dessert('Coconut slice and frozen yogurt', 318, 21.0, 31, 5.5, 96, 14, 7),
    Dessert('Coconut and ice cream sandwich', 396, 24.0, 44, 5.8, 138, 8, 7),
    Dessert('Coconut slice and eclair', 421, 31.0, 31, 7.5, 346, 6, 13),
    Dessert('Coconut slice and cupcake', 464, 18.7, 74, 5.8, 422, 3, 14),
    Dessert('Coconut slice and gingerbread', 515, 31.0, 56, 5.4, 316, 7, 22),
    Dessert('Coconut slice and jelly bean', 534, 15.0, 101, 1.5, 59, 0, 6),
    Dessert('Coconut slice and lollipop', 551, 15.2, 105, 1.5, 47, 0, 8),
    Dessert('Coconut slice and honeycomb', 567, 18.2, 94, 8.0, 571, 0, 51),
    Dessert('Coconut slice and donut', 611, 40.0, 58, 6.4, 335, 2, 28),
    Dessert('Coconut slice and KitKat', 677, 41.0, 72, 8.5, 63, 12, 12),
  ];
*/