// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTAxCX1kyvpWC3NST_zgxd7XoHG_THC7U',
    appId: '1:195961268898:web:1331e7c4b6fe72e99e05fb',
    messagingSenderId: '195961268898',
    projectId: 'quinmat-project',
    authDomain: 'quinmat-project.firebaseapp.com',
    storageBucket: 'quinmat-project.appspot.com',
    measurementId: 'G-NHQE5CF5N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqzuYfJkp4hMi2HxS9pWvg7y7Na4FsU4M',
    appId: '1:195961268898:android:874f0830fbf8d4f79e05fb',
    messagingSenderId: '195961268898',
    projectId: 'quinmat-project',
    storageBucket: 'quinmat-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyC_4mbnbh56hWG-nYNZ5VAuzp1QIDGv8',
    appId: '1:195961268898:ios:344f2380a8eab1f29e05fb',
    messagingSenderId: '195961268898',
    projectId: 'quinmat-project',
    storageBucket: 'quinmat-project.appspot.com',
    iosClientId: '195961268898-u9s2sjdrsvke6cemo1f50j1n3krlta84.apps.googleusercontent.com',
    iosBundleId: 'com.quinmat.qmtManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyC_4mbnbh56hWG-nYNZ5VAuzp1QIDGv8',
    appId: '1:195961268898:ios:344f2380a8eab1f29e05fb',
    messagingSenderId: '195961268898',
    projectId: 'quinmat-project',
    storageBucket: 'quinmat-project.appspot.com',
    iosClientId: '195961268898-u9s2sjdrsvke6cemo1f50j1n3krlta84.apps.googleusercontent.com',
    iosBundleId: 'com.quinmat.qmtManager',
  );
}
